theme: jekyll-theme-cayman
timezone: Europe/Helsinki
title: cmaster11's Warp Zone
future: true

plugins:
- jekyll-coffeescript
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings